# Autogenerated by devscripts/update-version.py

__version__ = '2024.04.19'

RELEASE_GIT_HEAD = '353c4c1c41a4c0b3b7689cdcd0fb06d025796798'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'DRM-Media-Tool/yt-dlp'

ORIGIN = 'DRM-Media-Tool/yt-dlp'

_pkg_version = '2024.04.19'
