# Autogenerated by devscripts/update-version.py

__version__ = '2024.02.14.010805'

RELEASE_GIT_HEAD = '4b9e230f091cbd540aff1e532f415546d5ee727a'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'DRM-Media-Tool/yt-dlp'

ORIGIN = 'DRM-Media-Tool/yt-dlp'

_pkg_version = '2024.02.14.010805'
