# Autogenerated by devscripts/update-version.py

__version__ = '2024.01.18.131236'

RELEASE_GIT_HEAD = 'bf85900b9c448255e6708ea9b31ddf672cd93453'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'Rajeshwaran2001/yt-dlp'

ORIGIN = 'Rajeshwaran2001/yt-dlp'

_pkg_version = '2024.01.18.131236'
